version: '3.8'

services:
  app:
    build:
      context: .
      args:
        - OPENAI_API_KEY=${OPENAI_API_KEY}
        - PINECONE_API_KEY=${PINECONE_API_KEY}
        - PINECONE_INDEX=${PINECONE_INDEX}
    ports:
      - "3001:3000"
    environment:
      - NODE_ENV=development
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - PINECONE_API_KEY=${PINECONE_API_KEY}
      - PINECONE_INDEX=${PINECONE_INDEX}
    env_file:
      - .env.local
    volumes:
      - .:/app
      - /app/node_modules
    restart: unless-stopped
    command: npm run dev
