server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: docker
    static_configs:
      - targets:
          - localhost
        labels:
          job: docker
          __path__: /var/lib/docker/containers/*/*-json.log
    pipeline_stages:
      - json:
          expressions:
            output: log
            stream: stream
            attrs: attrs
            level: level
      - labels:
          stream:
          level:
          container_name:
      - output:
          source: output

  - job_name: app-logs
    static_configs:
      - targets:
          - localhost
        labels:
          job: app
          service: transcription
          __path__: /var/lib/docker/containers/*app*.log
    pipeline_stages:
      - json:
          expressions:
            message: log
            level: level
            component: component
      - labels:
          level:
          component:
      - output:
          source: message
